//! Engineering observations. Collection has explicit filesystem, command and network context;
//! expression evaluation belongs to Canon and never calls this crate during offline replay.
mod files;
mod network;
mod process;
mod reports;
/// ESS-generated wire contract, shared with external Rust providers.
#[rustfmt::skip]
#[allow(clippy::derivable_impls)] // Preserve ESS 0.55.0's generated bytes.
#[path = "../generated/types.rs"]
pub mod contract;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::{collections::BTreeMap, fmt, path::PathBuf, time::Duration};

#[derive(Debug, Clone, PartialEq)]
pub enum Collected {
    Known(Value),
    Unavailable(String),
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProviderError {
    Invalid(String),
    Io(std::io::ErrorKind, String),
}
impl fmt::Display for ProviderError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Invalid(message) | Self::Io(_, message) => f.write_str(message),
        }
    }
}
impl std::error::Error for ProviderError {}
impl From<std::io::Error> for ProviderError {
    fn from(e: std::io::Error) -> Self {
        Self::Io(e.kind(), e.to_string())
    }
}
impl From<serde_json::Error> for ProviderError {
    fn from(e: serde_json::Error) -> Self {
        Self::Invalid(e.to_string())
    }
}

/// Admission is caller-owned. These are explicit argv/env bindings, never shell source.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CommandBinding {
    pub executable: PathBuf,
    #[serde(default)]
    pub args: Vec<String>,
    #[serde(default)]
    pub env: BTreeMap<String, String>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExternalProvider {
    pub identity: String,
    pub sha256: String,
    pub command: CommandBinding,
}
/// Explicit host-to-IP bindings keep TCP from silently depending on the host's DNS setup.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NetworkBinding {
    pub hosts: BTreeMap<String, std::net::IpAddr>,
}
#[derive(Debug, Clone)]
pub struct ProviderContext {
    pub root: PathBuf,
    pub commands: BTreeMap<String, CommandBinding>,
    pub providers: BTreeMap<String, ExternalProvider>,
    pub networks: BTreeMap<String, NetworkBinding>,
    pub timeout: Duration,
    pub max_output_bytes: usize,
}
impl ProviderContext {
    pub fn new(root: impl Into<PathBuf>) -> Self {
        Self {
            root: root.into(),
            commands: BTreeMap::new(),
            providers: BTreeMap::new(),
            networks: BTreeMap::new(),
            timeout: Duration::from_secs(10),
            max_output_bytes: 4 * 1024 * 1024,
        }
    }
}
pub type Arguments = BTreeMap<String, Value>;
/// Closed built-in operation names. Catalog extensions introduce recipes or registered processes.
pub const OPERATIONS: &[&str] = &[
    "fs.file.exists",
    "fs.dir.exists",
    "text.contains",
    "json.read",
    "yaml.read",
    "document.get",
    "document.validates",
    "generated.matches",
    "process.run",
    "process.succeeded",
    "tests.report",
    "tests.run",
    "codegate.dependencies",
    "ess.report",
    "ess.run",
    "net.host.resolves",
    "net.tcp.reachable",
];
pub(crate) fn arg<'a>(args: &'a Arguments, key: &str) -> Result<&'a str, ProviderError> {
    args.get(key)
        .and_then(Value::as_str)
        .ok_or_else(|| ProviderError::Invalid(format!("argument {key} must be a string")))
}
pub(crate) fn known(value: impl Into<Value>) -> Result<Collected, ProviderError> {
    Ok(Collected::Known(value.into()))
}
/// Collect one request. Invalid configuration or malformed producer data is a hard error;
/// environmental inability is Unavailable. Definitive negative observations remain Known(false).
pub fn collect(
    operation: &str,
    args: &Arguments,
    context: &ProviderContext,
) -> Result<Collected, ProviderError> {
    match collect_inner(operation, args, context) {
        Err(ProviderError::Io(_, message)) => Ok(Collected::Unavailable(message)),
        result => result,
    }
}
fn collect_inner(
    operation: &str,
    args: &Arguments,
    context: &ProviderContext,
) -> Result<Collected, ProviderError> {
    if context.timeout.is_zero()
        || context.timeout > Duration::from_secs(300)
        || context.max_output_bytes == 0
        || context.max_output_bytes > 16 * 1024 * 1024
    {
        return Err(ProviderError::Invalid("invalid collection limits".into()));
    }
    if context.providers.contains_key(operation) {
        return process::external(operation, args, context);
    }
    match operation {
        "fs.file.exists" | "fs.dir.exists" | "text.contains" | "json.read" | "yaml.read"
        | "document.get" | "document.validates" | "generated.matches" => {
            files::collect(operation, args, context)
        }
        "process.run" | "ess.run" => process::collect(args, context),
        "process.succeeded" => match process::collect(args, context)? {
            Collected::Known(value) => match value.get("exit_code").and_then(Value::as_i64) {
                Some(code) => known(code == 0),
                None => Ok(Collected::Unavailable(
                    "process ended without an exit code".into(),
                )),
            },
            unavailable => Ok(unavailable),
        },
        "tests.report" | "tests.run" | "codegate.dependencies" | "ess.report" => {
            reports::collect(operation, args, context)
        }
        "net.host.resolves" => network::dns(args, context),
        "net.tcp.reachable" => network::tcp(args, context),
        _ => Err(ProviderError::Invalid(format!(
            "unregistered operation: {operation}"
        ))),
    }
}
/// SHA-256 of an admitted executable, also used by catalog-lock generation.
pub fn executable_digest(path: &std::path::Path) -> Result<String, ProviderError> {
    use sha2::{Digest, Sha256};
    let mut file = std::fs::File::open(path)?;
    let mut hash = Sha256::new();
    std::io::copy(&mut file, &mut hash)?;
    Ok(format!("{:x}", hash.finalize()))
}
