//! Text from a document, made safe for CommonMark (the site reads `.md` files as CommonMark, not
//! MDX) and for Mermaid labels.

use b10x_canon::model::one_line;

/// The first line of every generated file's front matter.
pub const HEADER: &str = "# generated by els-docs, do not edit";

/// Prose from a document: Canon's `one_line` writes control, format and bidirectional characters
/// as visible escapes, then every character Markdown or a table could read as syntax is escaped.
pub fn text(source: &str) -> String {
    let mut out = String::with_capacity(source.len());
    for c in one_line(source).chars() {
        if matches!(
            c,
            '\\' | '`'
                | '*'
                | '_'
                | '['
                | ']'
                | '<'
                | '>'
                | '|'
                | '#'
                | '~'
                | '&'
                | '!'
                | '{'
                | '}'
        ) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

/// An identifier as a code span, safe inside a table cell.
pub fn code(source: &str) -> String {
    let shown = one_line(source).replace('|', "\\|");
    let mut longest = 0;
    let mut run = 0;
    for c in shown.chars() {
        run = if c == '`' { run + 1 } else { 0 };
        longest = longest.max(run);
    }
    let fence = "`".repeat(longest + 1);
    let pad = if shown.starts_with('`') || shown.ends_with('`') {
        " "
    } else {
        ""
    };
    format!("{fence}{pad}{shown}{pad}{fence}")
}

/// A front-matter string value: a JSON string is a valid YAML double-quoted scalar.
pub fn yaml_string(source: &str) -> String {
    serde_json::Value::String(one_line(source)).to_string()
}

/// A Mermaid node label, written inside double quotes.
pub fn mermaid_label(source: &str) -> String {
    let mut out = String::new();
    for c in one_line(source).chars() {
        match c {
            '#' => out.push_str("#35;"),
            '"' => out.push_str("#quot;"),
            '<' => out.push_str("#lt;"),
            '>' => out.push_str("#gt;"),
            '&' => out.push_str("#amp;"),
            '`' => out.push_str("#96;"),
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn markup_cannot_escape_its_context() {
        assert_eq!(text("<b>|x_y"), "\\<b\\>\\|x\\_y");
        assert_eq!(text("a\u{202e}b"), "a\\\\u\\{202e\\}b");
        assert_eq!(code("a`b"), "``a`b``");
        assert_eq!(code("`a"), "`` `a ``");
        assert_eq!(code("a|b"), "`a\\|b`");
        assert_eq!(yaml_string("say \"hi\""), "\"say \\\"hi\\\"\"");
        assert_eq!(mermaid_label("a\"#<b>"), "a#quot;#35;#lt;b#gt;");
    }
}
