//! Adversary pass 1 on `story:crate-rename`, docs generator side: its clap surface names
//! `canon-engineering-docs`, a drift failure tells the reader the renamed command to run, and a
//! fresh render of every generated file names no project `ELS`.

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn docs(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_canon-engineering-docs"))
        .args(args)
        .output()
        .unwrap_or_else(|error| panic!("canon-engineering-docs {}: {error}", args.join(" ")))
}

/// `grep -iw` semantics for one word.
fn has_word(text: &str, word: &str) -> bool {
    let lower = text.to_ascii_lowercase();
    let word = word.to_ascii_lowercase();
    let is_word = |c: char| c.is_ascii_alphanumeric() || c == '_';
    let mut from = 0;
    while let Some(found) = lower[from..].find(&word) {
        let start = from + found;
        let end = start + word.len();
        let before = lower[..start].chars().next_back();
        let after = lower[end..].chars().next();
        if !before.is_some_and(is_word) && !after.is_some_and(is_word) {
            return true;
        }
        from = start + 1;
    }
    false
}

fn root() -> PathBuf {
    PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("run through cargo")).join("../..")
}

fn copy_tree(from: &Path, to: &Path) {
    std::fs::create_dir_all(to).expect("mkdir");
    for entry in std::fs::read_dir(from).expect("read_dir").flatten() {
        let name = entry.file_name();
        let lossy = name.to_string_lossy();
        if lossy == "node_modules" || lossy == "build" || lossy == ".docusaurus" {
            continue;
        }
        let path = entry.path();
        if path.is_dir() {
            copy_tree(&path, &to.join(&name));
        } else {
            std::fs::copy(&path, to.join(&name)).expect("copy");
        }
    }
}

fn fresh_root(name: &str) -> PathBuf {
    let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR"))
        .join(format!("adversary-rename-{}-{name}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    copy_tree(&root().join("protocols"), &dir.join("protocols"));
    copy_tree(&root().join("website"), &dir.join("website"));
    dir
}

#[test]
fn help_names_the_renamed_command() {
    let out = docs(&["--help"]);
    assert_eq!(out.status.code(), Some(0), "{out:?}");
    let stdout = String::from_utf8(out.stdout).expect("UTF-8");
    assert!(
        stdout.contains("Usage: canon-engineering-docs <COMMAND>"),
        "help names canon-engineering-docs:\n{stdout}"
    );
    assert!(!has_word(&stdout, "els"), "help names ELS:\n{stdout}");
}

#[test]
fn drift_names_the_renamed_command_to_run() {
    let dir = fresh_root("drift");
    let page = dir.join("website/docs/vocabulary.md");
    let mut text = std::fs::read_to_string(&page).expect("vocabulary page");
    text.push_str("\nstale\n");
    std::fs::write(&page, text).expect("write");
    let out = docs(&[
        "generate",
        "--check",
        "--root",
        dir.to_str().expect("UTF-8 path"),
    ]);
    assert_ne!(
        out.status.code(),
        Some(0),
        "a stale page fails --check: {out:?}"
    );
    let stderr = String::from_utf8(out.stderr).expect("UTF-8");
    assert!(
        stderr.contains("run `canon-engineering-docs generate`"),
        "the drift message names the renamed command:\n{stderr}"
    );
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn a_fresh_render_names_no_project_els() {
    let dir = fresh_root("render");
    let out = docs(&["generate", "--root", dir.to_str().expect("UTF-8 path")]);
    assert_eq!(out.status.code(), Some(0), "generate: {out:?}");
    let mut offenders = Vec::new();
    let mut headers = 0;
    let mut stack = vec![dir.join("website/docs"), dir.join("website/data")];
    while let Some(path) = stack.pop() {
        if path.is_dir() {
            for entry in std::fs::read_dir(&path).expect("read_dir").flatten() {
                stack.push(entry.path());
            }
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue;
        };
        let generated_data = path.starts_with(dir.join("website/data/protocol-graphs"))
            || path.starts_with(dir.join("website/data/example-graphs"))
            || path == dir.join("website/data/status.json");
        if text.contains("generated by canon-engineering-docs, do not edit") {
            headers += 1;
        } else if !generated_data {
            continue;
        }
        assert!(
            !text.contains("generated by els-docs"),
            "{} still carries the old header",
            path.display()
        );
        for (n, line) in text.lines().enumerate() {
            if has_word(line, "els")
                && !line.contains("github.com/beyond10x/els")
                && !line.contains("/els/")
            {
                offenders.push(format!("{}:{}: {line}", path.display(), n + 1));
            }
        }
    }
    assert!(
        headers >= 4,
        "generated pages carry the renamed header: {headers}"
    );
    assert!(
        offenders.is_empty(),
        "generated text names ELS:\n{}",
        offenders.join("\n")
    );
    let _ = std::fs::remove_dir_all(&dir);
}
