//! Adversary pass 1 on `story:crate-rename`, docs generator side: its clap surface names
//! `canon-engineering-docs`, a drift failure tells the reader the renamed command to run, and a
//! fresh render of every generated file names no project `ELS`.
//!
//! `story:repository-rename` tightened it: the repository is `beyond10x/engineering-protocols`,
//! served under `/engineering-protocols/`, so a fresh render may no longer link
//! `github.com/beyond10x/els` or the `/els/` route, its source links name the new repository, and
//! the site manifest the publisher checks declares the new repository and route.

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn docs(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_canon-engineering-docs"))
        .args(args)
        .output()
        .unwrap_or_else(|error| panic!("canon-engineering-docs {}: {error}", args.join(" ")))
}

/// `grep -iw` semantics for one word.
fn has_word(text: &str, word: &str) -> bool {
    let lower = text.to_ascii_lowercase();
    let word = word.to_ascii_lowercase();
    let is_word = |c: char| c.is_ascii_alphanumeric() || c == '_';
    let mut from = 0;
    while let Some(found) = lower[from..].find(&word) {
        let start = from + found;
        let end = start + word.len();
        let before = lower[..start].chars().next_back();
        let after = lower[end..].chars().next();
        if !before.is_some_and(is_word) && !after.is_some_and(is_word) {
            return true;
        }
        from = start + 1;
    }
    false
}

fn root() -> PathBuf {
    PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("run through cargo")).join("../..")
}

fn copy_tree(from: &Path, to: &Path) {
    std::fs::create_dir_all(to).expect("mkdir");
    for entry in std::fs::read_dir(from).expect("read_dir").flatten() {
        let name = entry.file_name();
        let lossy = name.to_string_lossy();
        if lossy == "node_modules" || lossy == "build" || lossy == ".docusaurus" {
            continue;
        }
        let path = entry.path();
        if path.is_dir() {
            copy_tree(&path, &to.join(&name));
        } else {
            std::fs::copy(&path, to.join(&name)).expect("copy");
        }
    }
}

fn fresh_root(name: &str) -> PathBuf {
    let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR"))
        .join(format!("adversary-rename-{}-{name}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    copy_tree(&root().join("protocols"), &dir.join("protocols"));
    copy_tree(&root().join("website"), &dir.join("website"));
    dir
}

#[test]
fn help_names_the_renamed_command() {
    let out = docs(&["--help"]);
    assert_eq!(out.status.code(), Some(0), "{out:?}");
    let stdout = String::from_utf8(out.stdout).expect("UTF-8");
    assert!(
        stdout.contains("Usage: canon-engineering-docs <COMMAND>"),
        "help names canon-engineering-docs:\n{stdout}"
    );
    assert!(!has_word(&stdout, "els"), "help names ELS:\n{stdout}");
}

#[test]
fn drift_names_the_renamed_command_to_run() {
    let dir = fresh_root("drift");
    let page = dir.join("website/docs/vocabulary.md");
    let mut text = std::fs::read_to_string(&page).expect("vocabulary page");
    text.push_str("\nstale\n");
    std::fs::write(&page, text).expect("write");
    let out = docs(&[
        "generate",
        "--check",
        "--root",
        dir.to_str().expect("UTF-8 path"),
    ]);
    assert_ne!(
        out.status.code(),
        Some(0),
        "a stale page fails --check: {out:?}"
    );
    let stderr = String::from_utf8(out.stderr).expect("UTF-8");
    assert!(
        stderr.contains("run `canon-engineering-docs generate`"),
        "the drift message names the renamed command:\n{stderr}"
    );
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn a_fresh_render_names_no_project_els() {
    let dir = fresh_root("render");
    let out = docs(&["generate", "--root", dir.to_str().expect("UTF-8 path")]);
    assert_eq!(out.status.code(), Some(0), "generate: {out:?}");
    let mut offenders = Vec::new();
    let mut headers = 0;
    let mut source_links = 0;
    let mut stack = vec![dir.join("website/docs"), dir.join("website/data")];
    while let Some(path) = stack.pop() {
        if path.is_dir() {
            for entry in std::fs::read_dir(&path).expect("read_dir").flatten() {
                stack.push(entry.path());
            }
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue;
        };
        let generated_data = path.starts_with(dir.join("website/data/protocol-graphs"))
            || path.starts_with(dir.join("website/data/example-graphs"))
            || path == dir.join("website/data/status.json");
        if text.contains("generated by canon-engineering-docs, do not edit") {
            headers += 1;
        } else if !generated_data {
            continue;
        }
        assert!(
            !text.contains("generated by els-docs"),
            "{} still carries the old header",
            path.display()
        );
        for (n, line) in text.lines().enumerate() {
            if has_word(line, "els") {
                offenders.push(format!("{}:{}: {line}", path.display(), n + 1));
            }
            if line.contains("https://github.com/beyond10x/engineering-protocols/blob/main/") {
                source_links += 1;
            }
        }
    }
    assert!(
        headers >= 4,
        "generated pages carry the renamed header: {headers}"
    );
    assert!(
        source_links >= 3,
        "the vocabulary and every protocol page link their source in beyond10x/engineering-protocols: {source_links}"
    );
    assert!(
        offenders.is_empty(),
        "generated text names ELS:\n{}",
        offenders.join("\n")
    );
    let _ = std::fs::remove_dir_all(&dir);
}

/// The binary's `site-manifest`, as `pages.yml` runs it, declares the renamed repository and route:
/// the project-site publisher refuses a site whose manifest disagrees with its `repository` and
/// `route_base`.
#[test]
fn the_site_manifest_declares_engineering_protocols() {
    let site = PathBuf::from(env!("CARGO_TARGET_TMPDIR"))
        .join(format!("adversary-rename-{}-manifest", std::process::id()));
    let _ = std::fs::remove_dir_all(&site);
    std::fs::create_dir_all(&site).expect("mkdir");
    std::fs::write(site.join("index.html"), "<!doctype html>\n").expect("index.html");
    let commit = "fef049470cf8fe4ca34ad0bf3694e6c25cdc9a74";
    let out = docs(&[
        "site-manifest",
        "--site",
        site.to_str().expect("UTF-8 path"),
        "--commit",
        commit,
    ]);
    assert_eq!(out.status.code(), Some(0), "site-manifest: {out:?}");
    let stdout = String::from_utf8(out.stdout).expect("UTF-8");
    assert!(
        stdout.contains(&format!("declared as engineering-protocols at {commit}")),
        "site-manifest reports the renamed repository:\n{stdout}"
    );
    // The site path is the caller's and may hold any word (a build dir named after a checkout).
    let message = stdout.replace(site.to_str().expect("UTF-8 path"), "<site>");
    assert!(
        !has_word(&message, "els"),
        "site-manifest names ELS:\n{stdout}"
    );
    let manifest: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(site.join(".well-known/b10x-site.json")).expect("manifest"),
    )
    .expect("manifest is JSON");
    assert_eq!(
        manifest,
        serde_json::json!({
            "schema": "b10x-project-site/v1",
            "repository": "engineering-protocols",
            "commit": commit,
            "baseUrl": "/engineering-protocols/",
        })
    );
    let _ = std::fs::remove_dir_all(&site);
}
