//! Generated public reference and the exact dependency model used by the ESS projection.
use anyhow::Result;
use canon_expr::Type;
use std::fmt::Write;

pub fn expression_model() -> String {
    format!(
        "# Generated from the pinned b10x-canon-expr MODEL_SPEC; do not edit.\n{}",
        canon_expr::MODEL_SPEC.replace("canon.expr", "engineering.expr")
    )
}
fn type_name(value: &Type) -> String {
    match value {
        Type::Scalar(value) => format!("{value:?}"),
        Type::List(value) => format!("List<{}>", type_name(value)),
        Type::Map(value) => format!("Map<String, {}>", type_name(value)),
        Type::Optional(value) => format!("Option<{}>", type_name(value)),
        Type::Record(fields) => format!(
            "{{{}}}",
            fields
                .iter()
                .map(|(k, v)| format!("{k}: {}", type_name(v)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}
pub fn reference() -> Result<String> {
    let mut output = String::from(
        "---\n# generated by canon-engineering-docs, do not edit\ntitle: Assertion catalog and CLI\nsidebar_position: 5\ndescription: Typed functions, recipes and command usage from the released implementation.\ncustom_edit_url: null\n---\n\nCatalog format: `canon-catalog/1`. Language: `canon-expr/1`.\n\n",
    );
    for (name, function) in crate::builtin_catalog()?.functions {
        writeln!(
            output,
            "## `{name}`\n\n```text\n{name}({}) -> {}\n```\n",
            function
                .parameters
                .iter()
                .map(|p| format!(
                    "{}: {}{}",
                    p.name,
                    type_name(&p.value_type),
                    p.default
                        .as_ref()
                        .map(|v| format!(" = {v:?}"))
                        .unwrap_or_default()
                ))
                .collect::<Vec<_>>()
                .join(", "),
            type_name(&function.returns)
        )?;
        match function.implementation {
            canon_expr::Implementation::Recipe(expression) => {
                writeln!(output, "Recipe:\n\n```text\n{expression}\n```\n")?
            }
            canon_expr::Implementation::Observation(provider) => writeln!(
                output,
                "Collects `{}` through `{}`. The implementation and bindings are locked into the plan at collection.\n",
                provider.operation, provider.provider
            )?,
            canon_expr::Implementation::Pure(builtin) => {
                writeln!(output, "Pure builtin: `{builtin:?}`.\n")?
            }
        }
    }
    use clap::Subcommand;
    let commands = [
        crate::cli::Assertions::augment_subcommands(clap::Command::new("assertions")),
        crate::cli::Gates::augment_subcommands(clap::Command::new("gates")),
    ];
    output.push_str("## Command line\n\nExit codes: 0 all true; 1 false; 2 invalid input/provider contract or IO error; 3 unknown.\n\n");
    for mut command in commands {
        let name = command.get_name().to_owned();
        writeln!(
            output,
            "```text\ncanon-engineering {name}\n{}\n```\n",
            command.render_long_help()
        )?;
        for child in command.get_subcommands_mut() {
            let name = child.get_name().to_owned();
            writeln!(
                output,
                "### `{name}`\n\n```text\n{}\n```\n",
                child.render_long_help()
            )?;
        }
    }
    let output = output
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    Ok(format!("{}\n", output.trim_end()))
}
