import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * One sidebar, generated from the docs tree. `index.md` (hand-written) comes first; `protocols/`
 * and `vocabulary.md` are written by `canon-engineering-docs generate`, which also sets their order.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
